spring:
  datasource:
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    generate-ddl: ${SPRING_JPA_HIBERNATE_GENERATE_DDL}
    open-in-view: ${SPRING_JPA_HIBERNATE_OPEN_IN_VIEW}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        show_sql: ${SPRING_JPA_HIBERNATE_PROPERTIES_HIBERNATE_SHOW_SQL}
        format_sql: ${SPRING_JPA_HIBERNATE_PROPERTIES_HIBERNATE_FORMAT_SQL}
        use_sql_comments: ${SPRING_JPA_HIBERNATE_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS}
        globally_quoted_identifiers: ${SPRING_JPA_HIBERNATE_PROPERTIES_HIBERNATE_GLOBALLY_QUOTED_IDENTIFIERS}
